[[redirects]]
from = "/search/:slug/"
to = "/.netlify/functions/search"
status = 200
force = true
_generated_by_eleventy_serverless = "search"

[[redirects]]
force = false
from = "/search"
status = 301
to = "/search/:slug/"

  [redirects.query]
  term = ":slug"

[build]
publish = "_site"
