[[redirects]]
_generated_by_eleventy_serverless = "color"
force = true
from = "/search/:query/"
status = 200
to = "/.netlify/functions/search"

[[redirects]]
from = "/post/"
status = 301
to = "/search/:query/"

  [redirects.query]
  query = ":query"

[build]
functions = "functions"
