[[redirects]]
_generated_by_eleventy_serverless = "serverless"
force = true
from = "/search/:slug/"
status = 200
to = "/.netlify/functions/serverless"

[[redirects]]
force = false
from = "/search"
status = 301
to = "/search/:slug/"

[redirects.query]
slug = ":slug"

[build]
publish = "_site/"

[build.environment]
NODE_VERSION = "v14.17.6"

[functions]
directory = "functions/"
