[[redirects]]
from = "/search/:slug/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
force = false
from = "/search"
status = 301
to = "/search/:slug/"

  [redirects.query]
  slug = ":slug"

[build]
functions = "functions"
