[[redirects]]
_generated_by_eleventy_serverless = "searchy"
force = true
from = "/search/*"
status = 200
to = "/.netlify/builders/searchy"

[[redirects]]
force = true
from = "/post/"
query = {query = ":query"}
status = 301
to = "/search/:query/"

[build]
functions = "functions"
